package it.develhope.loginSystem1.auth.controllers;

import it.develhope.loginSystem1.auth.entities.LoginDTO;
import it.develhope.loginSystem1.auth.entities.LoginRTO;
import it.develhope.loginSystem1.auth.services.LoginService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * @author Drumstyle92
 * REST controller class used to handle user login requests
 */
@RestController
@RequestMapping("/auth")
public class LoginController {

    /**
     * Dependency with @Autowired annotation to inject the LoginService into the controller
     */
    @Autowired
    private LoginService loginService;

    /**
     * @param loginDTO Parameter that takes a LoginDTO type object which contains the user's credentials
     * @return returns an object of type LoginRTO containing the
     *         authenticated user and a JWT (JSON Web Token) generated by the service
     * @throws Exception the exception
     * method that is called when the user sends a login request
     * via an HTTP POST request. If the login is unsuccessful, the method throws an exception
     */
    @PostMapping("/login")
    public LoginRTO login(@RequestBody LoginDTO loginDTO) throws Exception {

        LoginRTO loginRto = loginService.login(loginDTO);

        if (loginRto == null) {

                throw new Exception("Cannot login");

            }

            return loginRto;

        }

    }
